### ISSUE TITLE
Mod causes ONI crash on build US1-600112-V

### ISSUE THREAD

**Issue by fstuff** [nathantalewis/oni-scaffolds#6]
OS: Windows 10 / Steam

On the latest ONI version, build  US1-600112-V, the mod causes the game to crash on loading a save that contains prior scaffold objects.  I also experienced a crash on a brand new game when attempting to build a scaffold for the first time.

I have narrowed the issue down to this mod by disabling all other mods and then attempting to load my prior save.  I did the same for a new game, and got the same result.

Crash logs attached.  

[Scaffold Error - loading older save.txt](https://github.com/nathantalewis/oni-scaffolds/files/14813323/Scaffold.Error.-.loading.older.save.txt)
[Scaffold Error - new game.txt](https://github.com/nathantalewis/oni-scaffolds/files/14813324/Scaffold.Error.-.new.game.txt)

**Comment by nathantalewis** [comment]
There is a chance that you are running into a Steam workshop caching issue where it hasn't actually detected the latest version of the mod since that error looks like one from about a month ago that should be fixed in the latest mod version.

Have you tried using the Mod Updater and letting it update the mods for you instead of just relying on Steam? It looks like it wasn't included in the list of mods based on those log files.

https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283

**Comment by fstuff** [comment]
Hi, that seems to have been the issue.  After I installed Mod Updater and forced an update to the Scaffolds mod it seems to be working now.  Thanks for the response, and for the mod. :)
